# Generated by Django 6.0.7 on 2026-08-03 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_rate', models.IntegerField(default=8)),
                ('meter_rent', models.IntegerField(default=60)),
                ('service_charge', models.IntegerField(default=25)),
                ('energy_tax', models.IntegerField(default=6)),
                ('green_cess', models.IntegerField(default=10)),
                ('fixed_charge', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariff Rates',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meter_no', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=120)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_location', models.CharField(max_length=50)),
                ('meter_type', models.CharField(max_length=50)),
                ('phase_code', models.CharField(max_length=30)),
                ('bill_type', models.CharField(max_length=30)),
                ('days', models.CharField(default='30', max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='billing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=20)),
                ('total_bill', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Not Paid', 'Not Paid'), ('Paid', 'Paid')], default='Not Paid', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.customer')),
            ],
            options={
                'unique_together': {('customer', 'month')},
            },
        ),
    ]
